# Generated by Django 5.1.7 on 2025-03-31 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='titie',
            new_name='title',
        ),
    ]
